server:
  port: 3000
  servlet:
    context-path: /api
spring:
  application:
    name: Bling
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${pickyboy.db.host}:3306/noteandtag?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${pickyboy.db.pw}
# Redis
  data:
    redis:
      host: localhost
      port: 6379
  # JSON??????
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.pickyboy: debug
    # 可以查看执行的SQL
    com.pickyboy.blingBackend.mapper: debug
  pattern:
    dateformat: HH:mm:ss:SSS

minio:
  endpoint: http://192.168.31.128:9000  # 您的MinIO服务器地址和端口
  access-key: minio           # 您的AccessKey
  secret-key: minio123           # 您的SecretKey
  bucket:                          # 定义不同上传类型的存储桶
    avatar: "bling-avatar"              # 头像存储桶
    resource: "bling-resources"          # 资源/文档存储桶
    cover: "bling-covers"                # 封面图片存储桶

# JWT
yuque:
  jwt:
    secret-key: "yuque-very-long-secret-key-for-jwt-2025"
    expire-hours: 24
    refresh-threshold-hours: 2
    token-prefix: "Bearer "
    header-name: "Authorization"
    auto-refresh: true

pickyboy:
  auth:
    excludePaths:
      - /api/auth/login
      - /api/auth/register
      - /api/uploads/**
      - /api/test/public
      - /error
      - /favicon.ico
      - /swagger-ui/**
      - /v3/api-docs/**
      - /doc.html
      - /webjars/**
      - /actuator/**

